name: CI

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    env:
      DISPLAY: ':99.0'
    steps:    
    - uses: actions/checkout@v4
    - name: Install system packages
      run: |
        sudo apt update
        sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils libgl1 libegl1 libdbus-1-3 libxcb-cursor0 libgtk-3-0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Print Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install typstwriter
      run: |
        pip install .
        pip install .[tests]
    - name: Start X
      run: |
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
    - name: Create trash directory
      run: |
        sudo mkdir -m 777 /tmp_pytest
    - name: Run tests
      run: |
        pytest
      env:
        PYTEST_DEBUG_TEMPROOT: /tmp_pytest
        
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install pip and ruff
      run: | 
        python -m pip install --upgrade pip
        pip install ruff
    - name: Run Ruff
      run: |
        ruff check --output-format=github
        ruff format --check
